apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: din-eliza-app
  name: din-eliza-app
  namespace: din-eliza
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: din-eliza-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: din-eliza-app
    spec:
      containers:
        - name: din-elia
          image: 992382680272.dkr.ecr.eu-west-3.amazonaws.com/sandbox-dev-din-eliza:main-5745199
          command: ["sh", "-c"]
          args: ["pnpm start --characters='characters/rag-eliza.json'"]
          ports:
            - containerPort: 3000
              protocol: TCP
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 300m
              memory: 1Gi
          envFrom:
            - secretRef:
                name: din-eliza-app
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 5
