---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: din-eliza-app
  labels:
    app.kubernetes.io/name: chat-server
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    name: din-eliza-app
    creationPolicy: Owner
  data:
  ## Refers to sandbox-dev-din-eliza-app-secrets in AWS Secrets Manager
  - secretKey: SLACK_CLIENT_SECRET
    remoteRef:
      key: din-eliza-app-secrets
      property: SLACK_CLIENT_SECRET
  - secretKey: SLACK_SIGNING_SECRET
    remoteRef:
      key: din-eliza-app-secrets
      property: SLACK_SIGNING_SECRET
  - secretKey: SLACK_BOT_TOKEN
    remoteRef:
      key: din-eliza-app-secrets
      property: SLACK_BOT_TOKEN
  - secretKey: SLACK_VERIFICATION_TOKEN
    remoteRef:
      key: din-eliza-app-secrets
      property: SLACK_VERIFICATION_TOKEN
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: din-eliza-app-secrets
      property: OPENAI_API_KEY