# Deployed in w3f sandbox dev environment, hackathon cluster
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: din-eliza
spec:
  project: apps-sandbox-dev
  destination:
    name: sandbox-dev-hackathon-eu
    namespace: din-eliza
  source:
    repoURL: https://github.com/ConsenSys/din-eliza.git
    path: deploy/w3f/app
    targetRevision: HEAD